before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/kubectl-snap.go
    binary: kubectl-snap
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - src: scripts/*
        strip_parent: true
        info:
          mode: 0775
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: sanderploegsma
    name: kubectl-snap

brews:
  - name: kubectl-snap
    tap:
      owner: sanderploegsma
      name: homebrew-tap
    description: Delete half of the pods in a Kubernetes cluster or namespace
    homepage: https://github.com/sanderploegsma/kubectl-snap
    install: |
      bin.install "kubectl-snap"
      bin.install "kubectl_complete-snap"
